### ISSUE TITLE
Please upgrade to ESLint 8.57

### ISSUE THREAD

**Issue by james-yeoman** [robinloeffel/esbuild-plugin-eslint#11]
ESLint 8.57 was [released 6 days ago](https://eslint.org/blog/2024/02/eslint-v8.57.0-released/), and includes a migration helper in the form of `loadESLint()`.

Given that ESLint v9 will require the use of the flat config format by default, I've been working on migrating my eslint config to the flat config format. However, this plugin is the last step in that migration.

In the meantime, I've copied the plugin into my codebase and modified it to use the `loadESLint` function. I'd prefer not to have this plugin code in my esbuild config file, since it doubles the size of the file alone.

**Comment by robinloeffel** [comment]
Thanks for raising this issue, I'll fix it asap!

**Comment by robinloeffel** [comment]
Hey man, I just published `v0.3.8`! While thinking about the issue at hand, it came to me that the crux probably isn't with the plugin here, since I only require ESLint as a peer dependency, and don't ship it with the package. So I suggest you try to update your local ESLint installation, and if you haven't explicitly defined it in your `package.json`, do some digging in your lock file on where it comes from.

I nevertheless took some time and updated the peer dependencies of esbuild and ESLint, anyways, and tested the plugin with `eslint@9.0.0-beta.1`, and everything still works fine!

**Comment by james-yeoman** [comment]
Thanks for the quick turn-around! I was mainly focused on the `loadESLint` helper, as it handles picking between the legacy cascade and the flat config classes based on what config is available at runtime. I guess the ESLint v9 beta is also a solution here.

Thanks for looking into this nonetheless
